services:
  washroom-service-debug:
    build:
      context: ./washroom-data-service
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/workspace
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    environment:
      - CGO_ENABLED=1
    working_dir: /workspace/washroom-data-service
    command: dlv debug --headless --listen=:40000 --api-version=2 --accept-multiclient --continue --allow-non-terminal-interactive .
    networks:
      - debug-network

networks:
  debug-network:
    name: debug-network
    driver: bridge
