services:
  washroom-service-debug:
    build:
      context: ./washroom-data-service
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - ./washroom-data-service:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/go/build
    environment:
      - CGO_ENABLED=1
    command: dlv debug --headless --listen=:40000 --api-version=2 --accept-multiclient --continue --allow-non-terminal-interactive -- build -gcflags="all=-N -l" .
    networks:
      - debug-network

volumes:
  go-mod-cache:
    driver: local
    driver_opts:
      type: none
      device: $HOME/.cache/go-mod
      o: bind
  go-build-cache:
    driver: local
  debug-cache:
    driver: local

networks:
  debug-network:
    name: debug-network
    driver: bridge
