FROM golang:1.23.6-alpine

# Install debugging dependencies
RUN apk add --no-cache gcc musl-dev sqlite-dev delve sqlite

WORKDIR /workspace/washroom-data-service

EXPOSE 8080 40000

CMD ["tail", "-f", "/dev/null"]
