FROM golang:1.23.6-alpine

# Install Air and required dependencies
RUN apk add --no-cache gcc musl-dev sqlite-dev git && \
    go install github.com/air-verse/air@latest

WORKDIR /app

# Copy go mod files for dependency download
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

EXPOSE 8080

ENV ENVIRONMENT=development \
    CGO_ENABLED=1 \
    GO111MODULE=on

# Run Air for hot reload
CMD ["air", "-c", ".air.toml"]
